var arr =["Gold","Silver","Aqua","Purple"]
var color1 =prompt("Enter color")
var color2 =prompt("Enter one more color")
var color3 =prompt("Enter one more color")
var color4 =prompt("Enter one more color")
arr.unshift(color1)
arr.unshift(color2)
arr.push(color3)
arr.push(color4)
arr.unshift("yellow")
arr.unshift("green")
arr.shift()
arr.pop()
var add =prompt("Enter index no. at which you want to add color")
var add2 =prompt("Enter color name what you want to add")
arr.splice(add,0,add2)
var delet =prompt("Enter index no. at which you want to delete color")
var delet2 =prompt("Enter number of deletion")
arr.splice(delet,delet2)
alert(arr)